apiVersion: v1
kind: Service
metadata:
  name: urbanboot-district-management-nodeport
  namespace: urbanboot
  labels:
    service: urbanboot-district-management-nodeport
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  selector:
    app: urban-district-management-app
  ports:
    - name: tcp
      port: 7200
      protocol: TCP
      targetPort: 7200
      nodePort: 30031
