apiVersion: v1
kind: Service
metadata:
  name: urbanboot-gateway-management-service
  namespace: urbanboot
  labels:
    service: urbanboot-gateway-management-service
spec:
  type: ClusterIP
  selector:
    app: urban-gateway-management-app
  ports:
    - name: tcp
      port: 7200
      protocol: TCP
      targetPort: 7200
