server:
  port: 7200
  tomcat:
    basedir: ./
    accesslog:
      enabled: true
      directory: logs
      pattern: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i"'
      prefix: access
      file-date-format: .yyyy-MM-dd
      suffix: .log
      rotate: true
      rename-on-rotate: true
      buffered: true
      request-attributes-enabled: true
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  config: classpath:logback/logback-config.xml
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
        beans:
          factory:
            support:
              DefaultListableBeanFactory: ERROR
        core:
          LocalVariableTableParameterNameDiscoverer: ERROR
          env:
            PropertySourcesPropertyResolver: ERROR
      hibernate: ERROR

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    local-cache-scope: SESSION
    lazy-loading-enabled: false
  mapper-locations: classpath*:mybatis/builder/*Mapper.xml

spring:
  application:
    name: urban-management-app
  cloud:
    consul:
      enabled: true
      host: ${autoconf.spring.cloud.service.discovery.consul.host}
      port: ${autoconf.spring.cloud.service.discovery.consul.port}
      scheme: http
      discovery:
        enabled: true
        service-name: urban-management-app
        tags: category=urbanboot, name=urban-management-app
        scheme: http
        fail-fast: true
        prefer-ip-address: true
        health-check-path: /health
        health-check-interval: 10s
        health-check-timeout: 5s
        health-check-critical-timeout: 30m
        heartbeat:
          enabled: true
          ttl-value: 30
      retry:
        initial-interval: 1000
        max-interval: 5000
        max-attempts: 6
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${autoconf.spring.datasource.endpoint}:${autoconf.spring.datasource.port}/${autoconf.spring.datasource.dbschema}?characterEncoding=UTF-8&autoReconnect=true&useSSL=true
    username: ${autoconf.spring.datasource.username}
    password: ${autoconf.spring.datasource.password}
    hikari:
      pool-name: UrbanManagementAppHikariCP
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 30000
      auto-commit: false
  jackson:
    dateFormat: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    timeZone: GMT
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DURATIONS_AS_TIMESTAMPS: true
    default-property-inclusion: ALWAYS